# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
rztpln <- function(n, mu, sigma) {
    .Call(`_poilog2_rztpln`, n, mu, sigma)
}

rztpois <- function(lambda) {
    .Call(`_poilog2_rztpois`, lambda)
}

