# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_dpln <- function(x, mu, sig) {
    .Call(`_ztpln_do_dpln`, x, mu, sig)
}

do_dpln2 <- function(x, mu, sig) {
    .Call(`_ztpln_do_dpln2`, x, mu, sig)
}

do_dztpln <- function(x, mu, sig) {
    .Call(`_ztpln_do_dztpln`, x, mu, sig)
}

do_dztpln2 <- function(x, mu, sig) {
    .Call(`_ztpln_do_dztpln2`, x, mu, sig)
}

do_dztplnm <- function(x, mu, sigma, theta) {
    .Call(`_ztpln_do_dztplnm`, x, mu, sigma, theta)
}

do_dztplnm2 <- function(x, mu, sigma, theta) {
    .Call(`_ztpln_do_dztplnm2`, x, mu, sigma, theta)
}

do_rztpln <- function(mu, sig) {
    .Call(`_ztpln_do_rztpln`, mu, sig)
}

do_vec_rztpln <- function(n, mu, sig) {
    .Call(`_ztpln_do_vec_rztpln`, n, mu, sig)
}

do_vec2_rztpln <- function(n, mu, sig) {
    .Call(`_ztpln_do_vec2_rztpln`, n, mu, sig)
}

